# Site/SEO settings
email: marti@josi.as
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:title/
google_analytics: 

name: Josias Marti
title: Josias Marti 
description: >
  das ist mein digitales Portfolio
url: https://josi.as

default_img: /assets/images/seo.jpg
social:
  - name: github
    url: https://github.com/creisey

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Josias Marti 
    bio: Josias Marti lebt in Luzern
    url: https://ai.josi.as

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
